using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Win32;

namespace PPGKoreanInstaller
{
    /// <summary>게임 폴더 찾기, 패치 설치/제거를 담당한다. (GUI와 분리)</summary>
    internal sealed class Patcher
    {
        public const string GameExe = "People Playground.exe";
        private const string ManifestRel = @"BepInEx\PPGKorean_install.txt";
        private const string PluginRel = @"BepInEx\plugins\PPGKorean\PPGKoreanFont.dll";
        private static readonly string[] LoaderFiles = { "winhttp.dll", "doorstop_config.ini", ".doorstop_version" };

        // 게임이 실행되면서 만드는 파일 (제거할 때 같이 지운다)
        private static readonly string[] GeneratedFiles =
        {
            @"BepInEx\LogOutput.log",
            @"BepInEx\PPGKorean_untranslated.txt",
            @"BepInEx\config\BepInEx.cfg",
            @"BepInEx\config\kr.ppg.koreanfont.cfg",
            @"BepInEx\config\gravydevsupreme.xunity.resourceredirector.cfg",
            @"BepInEx\Translation\ko\Text\_AutoGeneratedTranslations.txt",
            @"BepInEx\Translation\ko\Text\_Postprocessors.txt",
            @"BepInEx\Translation\ko\Text\_Preprocessors.txt",
            @"BepInEx\Translation\ko\Text\_Substitutions.txt",
        };
        private static readonly string[] GeneratedDirs = { @"BepInEx\cache" };

        private readonly string _game;
        private readonly Action<string> _log;
        private readonly Action<int, int> _progress;

        public Patcher(string gameDir, Action<string> log, Action<int, int> progress)
        {
            _game = gameDir;
            _log = log ?? (s => { });
            _progress = progress ?? ((a, b) => { });
        }

        // ── 상태 ──
        public static bool IsGameDir(string dir)
        {
            return !string.IsNullOrEmpty(dir) && File.Exists(Path.Combine(dir, GameExe))
                   && Directory.Exists(Path.Combine(dir, "People Playground_Data"));
        }

        public bool IsInstalled { get { return File.Exists(Path.Combine(_game, PluginRel)); } }

        public string InstalledVersion
        {
            get
            {
                string m = Path.Combine(_game, ManifestRel);
                if (!File.Exists(m)) return IsInstalled ? "알 수 없음(수동 설치)" : null;
                string first = File.ReadLines(m).FirstOrDefault() ?? "";
                return first.StartsWith("version=") ? first.Substring(8) : "알 수 없음";
            }
        }

        /// <summary>이 폴더의 게임이 실행 중인지 (경로를 알 수 없으면 실행 중으로 본다)</summary>
        public bool GameRunning
        {
            get
            {
                string exe = Path.GetFullPath(Path.Combine(_game, GameExe));
                foreach (Process p in Process.GetProcessesByName("People Playground"))
                {
                    try
                    {
                        if (string.Equals(Path.GetFullPath(p.MainModule.FileName), exe, StringComparison.OrdinalIgnoreCase)) return true;
                    }
                    catch { return true; }
                }
                return false;
            }
        }

        /// <summary>BepInEx가 아닌 다른 로더(winhttp.dll)가 있으면 설명을, 없으면 null을 돌려준다.</summary>
        public string ForeignLoader()
        {
            string dll = Path.Combine(_game, "winhttp.dll");
            if (!File.Exists(dll)) return null;
            string ini = Path.Combine(_game, "doorstop_config.ini");
            if (!File.Exists(ini)) return "설정 파일 없이 winhttp.dll만 있습니다 (정체를 알 수 없는 로더)";
            string target = null;
            foreach (string raw in File.ReadAllLines(ini))
            {
                string line = raw.Trim();
                if (line.StartsWith("#") || line.StartsWith(";")) continue;
                var m = Regex.Match(line, @"^target_assembly\s*=\s*(.+)$", RegexOptions.IgnoreCase);
                if (m.Success) target = m.Groups[1].Value.Trim().Trim('"');
            }
            if (target == null) return "doorstop_config.ini에 대상이 적혀 있지 않은 로더";
            if (target.Replace('/', '\\').EndsWith(@"BepInEx\core\BepInEx.Preloader.dll", StringComparison.OrdinalIgnoreCase)) return null;
            return "BepInEx가 아닌 다른 로더가 설치되어 있습니다 (" + Path.GetFileName(target) + ")";
        }

        public bool CanWrite()
        {
            try
            {
                string probe = Path.Combine(_game, ".ppgk_write_test");
                File.WriteAllText(probe, "x");
                File.Delete(probe);
                return true;
            }
            catch (UnauthorizedAccessException) { return false; }
            catch (IOException) { return false; }
        }

        // ── 게임 폴더 자동 찾기 (Steam 라이브러리 전체) ──
        public const string AppId = "1118200";

        /// <summary>
        /// 게임 폴더 후보. Steam이 실제로 실행하는 폴더가 맨 앞에 온다.
        /// 게임을 다른 드라이브로 옮기면 예전 폴더가 남아 있을 수 있는데, 거기 설치하면 한국어가 나오지 않는다.
        /// </summary>
        public static List<string> FindGameDirs()
        {
            string active = SteamGameDir();
            var found = new List<string>();
            if (active != null) found.Add(active);
            foreach (string dir in AllGameDirs())
                if (!found.Contains(dir, StringComparer.OrdinalIgnoreCase)) found.Add(dir);
            return found;
        }

        /// <summary>Steam이 이 게임을 설치해 둔(=실행하는) 폴더. libraryfolders.vdf에서 게임 번호가 적힌 라이브러리를 찾는다.</summary>
        public static string SteamGameDir()
        {
            foreach (string root in SteamRoots())
            {
                string vdf = Path.Combine(root, @"steamapps\libraryfolders.vdf");
                if (!File.Exists(vdf)) continue;
                try
                {
                    string text = File.ReadAllText(vdf);
                    MatchCollection paths = Regex.Matches(text, "\"path\"\\s+\"([^\"]+)\"");
                    for (int i = 0; i < paths.Count; i++)
                    {
                        // 이 라이브러리 블록 = 이번 "path"부터 다음 "path" 전까지
                        int start = paths[i].Index;
                        int end = i + 1 < paths.Count ? paths[i + 1].Index : text.Length;
                        if (!Regex.IsMatch(text.Substring(start, end - start), "\"" + AppId + "\"\\s+\"")) continue;
                        string lib = paths[i].Groups[1].Value.Replace(@"\\", @"\");
                        string dir = GameDirInLibrary(lib);
                        if (dir != null) return dir;
                    }
                }
                catch { }
            }
            return null;
        }

        /// <summary>라이브러리 안의 게임 폴더 (appmanifest의 installdir을 따른다)</summary>
        private static string GameDirInLibrary(string lib)
        {
            string name = "People Playground";
            try
            {
                string acf = Path.Combine(lib, @"steamapps\appmanifest_" + AppId + ".acf");
                if (File.Exists(acf))
                {
                    Match m = Regex.Match(File.ReadAllText(acf), "\"installdir\"\\s+\"([^\"]+)\"");
                    if (m.Success) name = m.Groups[1].Value;
                }
            }
            catch { }
            string dir = Path.Combine(lib, "steamapps", "common", name);
            return IsGameDir(dir) ? dir : null;
        }

        public static bool SameDir(string a, string b)
        {
            if (string.IsNullOrEmpty(a) || string.IsNullOrEmpty(b)) return false;
            try
            {
                return string.Equals(Path.GetFullPath(a).TrimEnd('\\'), Path.GetFullPath(b).TrimEnd('\\'), StringComparison.OrdinalIgnoreCase);
            }
            catch { return false; }
        }

        private static List<string> SteamRoots()
        {
            var steamRoots = new List<string>();
            foreach (var (hive, key, name) in new[]
            {
                (Registry.CurrentUser, @"Software\Valve\Steam", "SteamPath"),
                (Registry.LocalMachine, @"SOFTWARE\WOW6432Node\Valve\Steam", "InstallPath"),
                (Registry.LocalMachine, @"SOFTWARE\Valve\Steam", "InstallPath"),
            })
            {
                try
                {
                    using (var k = hive.OpenSubKey(key))
                    {
                        string v = k?.GetValue(name) as string;
                        if (!string.IsNullOrEmpty(v)) steamRoots.Add(v.Replace('/', '\\'));
                    }
                }
                catch { }
            }
            steamRoots.Add(@"C:\Program Files (x86)\Steam");
            return steamRoots.Distinct(StringComparer.OrdinalIgnoreCase).ToList();
        }

        private static List<string> AllGameDirs()
        {
            var libraries = new List<string>();
            foreach (string root in SteamRoots())
            {
                libraries.Add(root);
                string vdf = Path.Combine(root, @"steamapps\libraryfolders.vdf");
                if (!File.Exists(vdf)) continue;
                try
                {
                    foreach (Match m in Regex.Matches(File.ReadAllText(vdf), "\"path\"\\s+\"([^\"]+)\""))
                        libraries.Add(m.Groups[1].Value.Replace(@"\\", @"\"));
                }
                catch { }
            }

            var found = new List<string>();
            foreach (string lib in libraries.Distinct(StringComparer.OrdinalIgnoreCase))
            {
                string dir = Path.Combine(lib, @"steamapps\common\People Playground");
                if (IsGameDir(dir) && !found.Contains(dir, StringComparer.OrdinalIgnoreCase)) found.Add(dir);
            }
            return found;
        }

        // ── 설치 ──
        public static string PayloadVersion { get { return Program.PatchVersion; } }

        /// <summary>그림 속 글자 한글화 조각이 들어 있는 폴더 (설치할 때 "글자만"을 고르면 넣지 않는다)</summary>
        public const string ImageDirRel = @"BepInEx\Translation\ko\Image\";

        public bool HasImages { get { return File.Exists(Path.Combine(_game, ImageDirRel + "index.txt")); } }

        /// <summary>그림 번역이 생긴 v0.3 이후 버전을 설치하면서 "글자만"을 골랐는지 (v0.2 이하는 고를 수 없었으므로 false)</summary>
        public bool TextOnlyChosen
        {
            get
            {
                string ver = InstalledVersion;
                Version v;
                return ver != null && !HasImages && ver.StartsWith("v") && Version.TryParse(ver.Substring(1), out v) && v >= new Version(0, 3);
            }
        }

        /// <param name="images">false면 글자만 번역한다 (그림 조각을 넣지 않고, 전에 넣은 것은 지운다)</param>
        public void Install(bool images)
        {
            if (GameRunning) throw new InvalidOperationException("게임이 실행 중입니다. 게임을 끈 뒤 다시 시도해 주세요.");
            if (!IsGameDir(_game)) throw new InvalidOperationException("선택한 폴더에 People Playground가 없습니다.");

            if (!images)
            {
                string imageDir = Path.Combine(_game, ImageDirRel);
                foreach (string rel in PayloadFiles().Where(IsImageFile))
                {
                    string full = Path.Combine(_game, rel);
                    if (File.Exists(full)) File.Delete(full);
                }
                RemoveEmptyDirs(imageDir);
            }

            string foreign = ForeignLoader();
            if (foreign != null)
            {
                string backup = Path.Combine(_game, "PPGKorean_backup", DateTime.Now.ToString("yyyyMMdd_HHmmss"));
                Directory.CreateDirectory(backup);
                foreach (string f in LoaderFiles)
                {
                    string src = Path.Combine(_game, f);
                    if (File.Exists(src)) File.Move(src, Path.Combine(backup, f));
                }
                _log("기존 로더를 백업했습니다: " + backup);
            }

            var installed = new List<string>();
            using (Stream payload = Assembly.GetExecutingAssembly().GetManifestResourceStream("payload.zip"))
            using (var zip = new ZipArchive(payload, ZipArchiveMode.Read, false, Encoding.UTF8))
            {
                var entries = zip.Entries.Where(e => e.Name.Length > 0).ToList();
                for (int i = 0; i < entries.Count; i++)
                {
                    ZipArchiveEntry e = entries[i];
                    string rel = MapEntry(e.FullName.Replace('/', '\\'));
                    if (rel != null && (images || !IsImageFile(rel)))
                    {
                        string dst = Path.Combine(_game, rel);
                        Directory.CreateDirectory(Path.GetDirectoryName(dst));
                        e.ExtractToFile(dst, true);
                        installed.Add(rel);
                    }
                    _progress(i + 1, entries.Count);
                }
            }
            var manifest = new List<string> { "version=" + PayloadVersion };
            manifest.AddRange(installed);
            File.WriteAllLines(Path.Combine(_game, ManifestRel), manifest, new UTF8Encoding(false));
            _log("파일 " + installed.Count + "개를 설치했습니다." + (images ? "" : " (글자만)"));
        }

        private static bool IsImageFile(string rel)
        {
            return rel.StartsWith(ImageDirRel, StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>zip 안의 경로를 게임 폴더 안의 경로로 바꾼다. null이면 설치하지 않는다.</summary>
        private static string MapEntry(string rel)
        {
            if (rel.Equals("설치방법.txt", StringComparison.OrdinalIgnoreCase)) return null;
            if (rel.Equals("changelog.txt", StringComparison.OrdinalIgnoreCase)) return null;
            if (rel.StartsWith(@"licenses\", StringComparison.OrdinalIgnoreCase))
                return @"BepInEx\PPGKorean_licenses\" + rel.Substring(9);
            return rel;
        }

        // ── 제거 ──
        public bool HasManifest { get { return File.Exists(Path.Combine(_game, ManifestRel)); } }

        /// <summary>설치 도우미 안에 든 패치 파일 목록 (게임 폴더 기준 경로)</summary>
        private static List<string> PayloadFiles()
        {
            using (Stream payload = Assembly.GetExecutingAssembly().GetManifestResourceStream("payload.zip"))
            using (var zip = new ZipArchive(payload, ZipArchiveMode.Read, false, Encoding.UTF8))
                return zip.Entries.Where(e => e.Name.Length > 0).Select(e => MapEntry(e.FullName.Replace('/', '\\'))).Where(r => r != null).ToList();
        }

        /// <summary>BepInEx 본체에 속하는 파일인지 (다른 플러그인이 쓰고 있으면 남겨야 하는 것)</summary>
        private static bool IsBepInExCore(string rel)
        {
            return LoaderFiles.Contains(rel, StringComparer.OrdinalIgnoreCase)
                   || rel.Equals("changelog.txt", StringComparison.OrdinalIgnoreCase)
                   || rel.StartsWith(@"BepInEx\core\", StringComparison.OrdinalIgnoreCase)
                   || rel.Equals(@"BepInEx\config\BepInEx.cfg", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>이 패치가 넣지 않은 BepInEx 플러그인/패처가 있는지</summary>
        private bool HasOtherPlugins(HashSet<string> ours)
        {
            foreach (string sub in new[] { @"BepInEx\plugins", @"BepInEx\patchers" })
            {
                string dir = Path.Combine(_game, sub);
                if (!Directory.Exists(dir)) continue;
                foreach (string f in Directory.GetFiles(dir, "*", SearchOption.AllDirectories))
                    if (!ours.Contains(f.Substring(_game.Length + 1))) return true;
            }
            return false;
        }

        public void Uninstall()
        {
            if (GameRunning) throw new InvalidOperationException("게임이 실행 중입니다. 게임을 끈 뒤 다시 시도해 주세요.");
            var targets = new List<string>();
            string manifest = Path.Combine(_game, ManifestRel);
            if (File.Exists(manifest)) targets.AddRange(File.ReadAllLines(manifest).Skip(1).Where(l => l.Length > 0));
            else
            {
                // 설치 기록이 없는 수동 설치: 이 패치에 든 파일만 지운다 (zip을 직접 풀었을 때 생기는 안내 파일 포함)
                targets.AddRange(PayloadFiles());
                targets.AddRange(new[]
                {
                    "설치방법.txt", "changelog.txt", @"licenses\BepInEx-LICENSE.txt", @"licenses\XUnity.AutoTranslator-LICENSE.txt",
                    @"licenses\LICENSE", @"licenses\THIRD_PARTY_NOTICES.md",
                });
            }
            targets.Add(ManifestRel);
            targets.Add(@"BepInEx\config\AutoTranslatorConfig.ini");

            var ours = new HashSet<string>(targets, StringComparer.OrdinalIgnoreCase);
            bool keepBepInEx = HasOtherPlugins(ours);
            targets.AddRange(GeneratedFiles);
            if (keepBepInEx)
            {
                targets = targets.Where(t => !IsBepInExCore(t)).ToList();
                _log("다른 BepInEx 플러그인이 있어서 BepInEx 본체는 남기고 한국어 패치 파일만 지웁니다.");
            }

            int removed = 0;
            for (int i = 0; i < targets.Count; i++)
            {
                string full = Path.Combine(_game, targets[i]);
                if (!full.StartsWith(_game, StringComparison.OrdinalIgnoreCase)) continue;
                if (File.Exists(full)) { File.Delete(full); removed++; }
                _progress(i + 1, targets.Count);
            }
            if (!keepBepInEx)
            {
                foreach (string d in GeneratedDirs)
                {
                    string full = Path.Combine(_game, d);
                    if (Directory.Exists(full)) Directory.Delete(full, true);
                }
            }
            RemoveEmptyDirs(Path.Combine(_game, "BepInEx"));
            RemoveEmptyDirs(Path.Combine(_game, "licenses"));
            _log("파일 " + removed + "개를 지웠습니다.");
            string bep = Path.Combine(_game, "BepInEx");
            if (Directory.Exists(bep)) _log("BepInEx 폴더에 다른 파일이 남아 있어 폴더는 그대로 두었습니다.");
        }

        private static void RemoveEmptyDirs(string dir)
        {
            if (!Directory.Exists(dir)) return;
            foreach (string sub in Directory.GetDirectories(dir)) RemoveEmptyDirs(sub);
            if (!Directory.EnumerateFileSystemEntries(dir).Any()) Directory.Delete(dir);
        }
    }
}
